#!/bin/sh
echo "
                    )  (    (        )  
          (      ( /(  )\ ) )\ )  ( /(  
 (   (    )\     )\())(()/((()/(  )\()) 
 )\  )\((((_)(  ((_)\  /(_))/(_))((_)\  
((_)((_))\ _ )\  _((_)(_)) (_))   _((_) 
\ \ / / (_)_\(_)| \| ||_ _|/ __| | || | 
 \ V /   / _ \  | .' | | | \__ \ | __ | 
  \_/   /_/ \_\ |_|\_||___||___/ |_||_| 
                                        
"
echo vanish - rev 2020.03 - ezekiel
echo " "
echo 1] encrypt
echo 2] decrypt
read CHOICE

if [ $CHOICE = 1 ]; then
	echo time to encrypt some stuff !
	echo enter the name of the folder:
	read FOLDER

	# Check if the folder exists
	if test ! -d "$FOLDER"; then
		echo "$FOLDER does not exist"
		exit
	fi

	# Zip and encrypt the folder
	zip -r $FOLDER.zip $FOLDER
	gpg -c $FOLDER.zip

	# Be sure that the previous command has not been aborted
	if [ $? != 0 ]; then
		exit $?
	fi

	# Remove/shred original folder and .zip file
	echo shredding garbage, this may take some time...
	shred --remove $FOLDER.zip
	rm -r $FOLDER
else
	echo time to recover your stuff !
	echo enter the name of the file:
	read FILE

	# Check if the file exists
	if test ! -f "$FILE.zip.gpg"; then
		echo "$FILE does not exist"
		exit
	fi

	# Decrypt and unzip the folder
	gpg $FILE.zip.gpg
	unzip $FILE.zip

	# Be sure that the previous command has not been aborted
	if [ $? != 0 ]; then
		exit $?
	fi

	# Shred and remove encrypted and zipped stuff
	echo shredding garbage, this may take some time...
	shred --remove $FILE.zip.gpg $FILE.zip
fi
