#!/bin/sh
echo "
                    )  (    (        )  
          (      ( /(  )\ ) )\ )  ( /(  
 (   (    )\     )\())(()/((()/(  )\()) 
 )\  )\((((_)(  ((_)\  /(_))/(_))((_)\  
((_)((_))\ _ )\  _((_)(_)) (_))   _((_) 
\ \ / / (_)_\(_)| \| ||_ _|/ __| | || | 
 \ V /   / _ \  | .' | | | \__ \ | __ | 
  \_/   /_/ \_\ |_|\_||___||___/ |_||_| 
                                        
"
echo vanish - rev 2020.03 - ezekiel
echo " "
echo 1] encrypt
echo 2] decrypt
echo 0] quit
read CHOICE

if [ $CHOICE = 1 ]; then
	echo time to encrypt some stuff !
	echo enter the name of the folder:
	read FOLDER

	# Check if the folder exists
	if test ! -d "$FOLDER"; then
		echo "$FOLDER does not exist or is already encrypted"
		sleep 1
		echo quitting...
		sleep 1
		exit
	fi

	# Zip and encrypt the folder
	zip -r $FOLDER.zip $FOLDER
	gpg -c $FOLDER.zip

	# Be sure that the previous command has not been aborted
	if [ $? != 0 ]; then
		exit $?
	fi

	# Remove/shred original folder and .zip file
	echo shredding garbage, this may take some time...
	echo "shredding $FOLDER.zip..."
	shred --remove -v $FOLDER.zip
	echo "shredding $FOLDER/..."
	srm -rfllv $FOLDER

elif [ $CHOICE = 2 ]; then
	echo time to recover your stuff !
	echo enter the name of the file:
	read FILE

	# Check if the file exists
	if test ! -f "$FILE.zip.gpg"; then
		echo "$FILE does not exist or is already decrypted"
		sleep 1
		echo quitting...
		sleep 1
		exit
	fi

	# Decrypt and unzip the folder
	gpg $FILE.zip.gpg
	unzip $FILE.zip

	# Be sure that the previous command has not been aborted
	if [ $? != 0 ]; then
		exit $?
	fi

	# Shred and remove encrypted and zipped stuff
	echo shredding garbage, this may take some time...
	echo "shredding $FILE.zip.gpg..."
	shred --remove -v $FILE.zip.gpg 
	echo "shredding $FILE.zip..."
	shred --remove -v $FILE.zip

elif [ $CHOICE = 0 ]; then
	echo quitting...
	sleep 0.5
	exit

else
	echo unknown input, quitting...
	sleep 0.5
	exit
fi
