#!/bin/bash


encrypt(){
	FOLDER=$1
	if test ! -d "$FOLDER"; then
		echo "$FOLDER does not exist or is already encrypted"
		sleep 1
		echo quitting...
		sleep 1
		exit
	fi

    if [ ${FOLDER: -1} == "/" ]; then
        FOLDER=${FOLDER%?}
    fi

	zip -r $FOLDER.zip $FOLDER
	gpg -c $FOLDER.zip

	# Be sure that the previous command has not been aborted
	if [ $? != 0 ]; then
		exit $?
	fi

	# Remove/shred original folder and .zip file
	echo shredding garbage, this may take some time...
	echo "shredding $FOLDER.zip..."
	shred --remove -v $FOLDER.zip
	echo "shredding $FOLDER/..."
	srm -rfllv $FOLDER
}

decrypt(){
	FILE=$1
	# Check if the file exists
	if test ! -f "$FILE"; then
		echo "$FILE does not exist or is already decrypted"
		sleep 1
		echo quitting...
		sleep 1
		exit
	fi

	# Decrypt and unzip the folder
	gpg $FILE
    unzip "${FILE%.*}"

	# Be sure that the previous command has not been aborted
	if [ $? != 0 ]; then
		exit $?
	fi

	# Shred and remove encrypted and zipped stuff
	echo shredding garbage, this may take some time...
	echo "shredding $FILE.zip.gpg..."
	shred --remove -v $FILE
	echo "shredding $FILE.zip..."
	shred --remove -v ${FILE%.*}
}

usage(){
	echo "
options :
	-e, --encrypt <folder name>
		encrypt a folder
	-d, --decrypt <file name>
		decrypt a file
	-h, --help
		show this help
	"
}
echo "
                    )  (    (        )  
          (      ( /(  )\ ) )\ )  ( /(  
 (   (    )\     )\())(()/((()/(  )\()) 
 )\  )\((((_)(  ((_)\  /(_))/(_))((_)\  
((_)((_))\ _ )\  _((_)(_)) (_))   _((_) 
\ \ / / (_)_\(_)| \| ||_ _|/ __| | || | 
 \ V /   / _ \  | .' | | | \__ \ | __ | 
  \_/   /_/ \_\ |_|\_||___||___/ |_||_| 
                                        
"
echo vanish - rev 2020.03 - ezekiel
echo " "

while [ "$1" != "" ]; do
	case $1 in
		-e | --encrypt )	shift
					encrypt $1
					shift
					;;
		-d | --decrypt )	shift
					decrypt $1
					shift
					;;
		-h | --help )		usage
					exit
					;;
	esac
done
